package com.social.commission.api.po;

import java.math.BigDecimal;
import java.util.Date;

public class CommissionOnePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.commission_one_id
     *
     * @mbg.generated
     */
    private Long commissionOneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.user_id
     *
     * @mbg.generated
     */
    private String userId;

    private String orderId;

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.good_id
     *
     * @mbg.generated
     */
    private String goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.commission_total_pre
     *
     * @mbg.generated
     */
    private BigDecimal commissionTotalPre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.commission_rate
     *
     * @mbg.generated
     */
    private String commissionRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.is_commission
     *
     * @mbg.generated
     */
    private String isCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.commission_time
     *
     * @mbg.generated
     */
    private Date commissionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_one.order_commission_time
     *
     * @mbg.generated
     */
    private Date orderCommissionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.commission_one_id
     *
     * @return the value of commission_one.commission_one_id
     *
     * @mbg.generated
     */
    public Long getCommissionOneId() {
        return commissionOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.commission_one_id
     *
     * @param commissionOneId the value for commission_one.commission_one_id
     *
     * @mbg.generated
     */
    public void setCommissionOneId(Long commissionOneId) {
        this.commissionOneId = commissionOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.user_id
     *
     * @return the value of commission_one.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.user_id
     *
     * @param userId the value for commission_one.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.order_sn
     *
     * @return the value of commission_one.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.order_sn
     *
     * @param orderSn the value for commission_one.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.good_id
     *
     * @return the value of commission_one.good_id
     *
     * @mbg.generated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.good_id
     *
     * @param goodId the value for commission_one.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.order_type
     *
     * @return the value of commission_one.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.order_type
     *
     * @param orderType the value for commission_one.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.commission_total_pre
     *
     * @return the value of commission_one.commission_total_pre
     *
     * @mbg.generated
     */
    public BigDecimal getCommissionTotalPre() {
        return commissionTotalPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.commission_total_pre
     *
     * @param commissionTotalPre the value for commission_one.commission_total_pre
     *
     * @mbg.generated
     */
    public void setCommissionTotalPre(BigDecimal commissionTotalPre) {
        this.commissionTotalPre = commissionTotalPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.order_status
     *
     * @return the value of commission_one.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.order_status
     *
     * @param orderStatus the value for commission_one.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.create_date
     *
     * @return the value of commission_one.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.create_date
     *
     * @param createDate the value for commission_one.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.update_date
     *
     * @return the value of commission_one.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.update_date
     *
     * @param updateDate the value for commission_one.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.commission_rate
     *
     * @return the value of commission_one.commission_rate
     *
     * @mbg.generated
     */
    public String getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.commission_rate
     *
     * @param commissionRate the value for commission_one.commission_rate
     *
     * @mbg.generated
     */
    public void setCommissionRate(String commissionRate) {
        this.commissionRate = commissionRate == null ? null : commissionRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.is_commission
     *
     * @return the value of commission_one.is_commission
     *
     * @mbg.generated
     */
    public String getIsCommission() {
        return isCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.is_commission
     *
     * @param isCommission the value for commission_one.is_commission
     *
     * @mbg.generated
     */
    public void setIsCommission(String isCommission) {
        this.isCommission = isCommission == null ? null : isCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.commission_time
     *
     * @return the value of commission_one.commission_time
     *
     * @mbg.generated
     */
    public Date getCommissionTime() {
        return commissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.commission_time
     *
     * @param commissionTime the value for commission_one.commission_time
     *
     * @mbg.generated
     */
    public void setCommissionTime(Date commissionTime) {
        this.commissionTime = commissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_one.order_commission_time
     *
     * @return the value of commission_one.order_commission_time
     *
     * @mbg.generated
     */
    public Date getOrderCommissionTime() {
        return orderCommissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_one.order_commission_time
     *
     * @param orderCommissionTime the value for commission_one.order_commission_time
     *
     * @mbg.generated
     */
    public void setOrderCommissionTime(Date orderCommissionTime) {
        this.orderCommissionTime = orderCommissionTime;
    }
}