package com.social.commission.api.po;

import java.math.BigDecimal;
import java.util.Date;

public class MainOrderPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_order.main_order_id
     *
     * @mbg.generated
     */
    private Long mainOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_order.pay_total
     *
     * @mbg.generated
     */
    private BigDecimal payTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_order.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_order.main_order_id
     *
     * @return the value of main_order.main_order_id
     *
     * @mbg.generated
     */
    public Long getMainOrderId() {
        return mainOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_order.main_order_id
     *
     * @param mainOrderId the value for main_order.main_order_id
     *
     * @mbg.generated
     */
    public void setMainOrderId(Long mainOrderId) {
        this.mainOrderId = mainOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_order.order_id
     *
     * @return the value of main_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_order.order_id
     *
     * @param orderId the value for main_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_order.pay_total
     *
     * @return the value of main_order.pay_total
     *
     * @mbg.generated
     */
    public BigDecimal getPayTotal() {
        return payTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_order.pay_total
     *
     * @param payTotal the value for main_order.pay_total
     *
     * @mbg.generated
     */
    public void setPayTotal(BigDecimal payTotal) {
        this.payTotal = payTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_order.create_date
     *
     * @return the value of main_order.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_order.create_date
     *
     * @param createDate the value for main_order.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}