package com.social.commission.api.po;

import java.math.BigDecimal;
import java.util.Date;

public class MallCommissionPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.mall_commission_id
     *
     * @mbg.generated
     */
    private Long mallCommissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.order_son
     *
     * @mbg.generated
     */
    private String orderSon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.commission_total_pre
     *
     * @mbg.generated
     */
    private BigDecimal commissionTotalPre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.order_person
     *
     * @mbg.generated
     */
    private String orderPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.commission_rate
     *
     * @mbg.generated
     */
    private String commissionRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_commission.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.mall_commission_id
     *
     * @return the value of mall_commission.mall_commission_id
     *
     * @mbg.generated
     */
    public Long getMallCommissionId() {
        return mallCommissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.mall_commission_id
     *
     * @param mallCommissionId the value for mall_commission.mall_commission_id
     *
     * @mbg.generated
     */
    public void setMallCommissionId(Long mallCommissionId) {
        this.mallCommissionId = mallCommissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.user_id
     *
     * @return the value of mall_commission.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.user_id
     *
     * @param userId the value for mall_commission.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.order_son
     *
     * @return the value of mall_commission.order_son
     *
     * @mbg.generated
     */
    public String getOrderSon() {
        return orderSon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.order_son
     *
     * @param orderSon the value for mall_commission.order_son
     *
     * @mbg.generated
     */
    public void setOrderSon(String orderSon) {
        this.orderSon = orderSon == null ? null : orderSon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.commission_total_pre
     *
     * @return the value of mall_commission.commission_total_pre
     *
     * @mbg.generated
     */
    public BigDecimal getCommissionTotalPre() {
        return commissionTotalPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.commission_total_pre
     *
     * @param commissionTotalPre the value for mall_commission.commission_total_pre
     *
     * @mbg.generated
     */
    public void setCommissionTotalPre(BigDecimal commissionTotalPre) {
        this.commissionTotalPre = commissionTotalPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.order_person
     *
     * @return the value of mall_commission.order_person
     *
     * @mbg.generated
     */
    public String getOrderPerson() {
        return orderPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.order_person
     *
     * @param orderPerson the value for mall_commission.order_person
     *
     * @mbg.generated
     */
    public void setOrderPerson(String orderPerson) {
        this.orderPerson = orderPerson == null ? null : orderPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.commission_rate
     *
     * @return the value of mall_commission.commission_rate
     *
     * @mbg.generated
     */
    public String getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.commission_rate
     *
     * @param commissionRate the value for mall_commission.commission_rate
     *
     * @mbg.generated
     */
    public void setCommissionRate(String commissionRate) {
        this.commissionRate = commissionRate == null ? null : commissionRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.order_status
     *
     * @return the value of mall_commission.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.order_status
     *
     * @param orderStatus the value for mall_commission.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.create_date
     *
     * @return the value of mall_commission.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.create_date
     *
     * @param createDate the value for mall_commission.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_commission.update_date
     *
     * @return the value of mall_commission.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_commission.update_date
     *
     * @param updateDate the value for mall_commission.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}