package com.social.commission.api.po;

import java.math.BigDecimal;
import java.util.Date;

public class OrderOnePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.order_one_id
     *
     * @mbg.generated
     */
    private Long orderOneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    private String orderId;

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.sub_order_sn
     *
     * @mbg.generated
     */
    private String subOrderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.terrace
     *
     * @mbg.generated
     */
    private String terrace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.commission_total_pre
     *
     * @mbg.generated
     */
    private BigDecimal commissionTotalPre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.commission_total_real
     *
     * @mbg.generated
     */
    private BigDecimal commissionTotalReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.is_commission
     *
     * @mbg.generated
     */
    private String isCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.product_img
     *
     * @mbg.generated
     */
    private String productImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.payment_price
     *
     * @mbg.generated
     */
    private String paymentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.commission_time
     *
     * @mbg.generated
     */
    private Date commissionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_one.reality_commission_time
     *
     * @mbg.generated
     */
    private Date realityCommissionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.order_one_id
     *
     * @return the value of order_one.order_one_id
     *
     * @mbg.generated
     */
    public Long getOrderOneId() {
        return orderOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.order_one_id
     *
     * @param orderOneId the value for order_one.order_one_id
     *
     * @mbg.generated
     */
    public void setOrderOneId(Long orderOneId) {
        this.orderOneId = orderOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.order_sn
     *
     * @return the value of order_one.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.order_sn
     *
     * @param orderSn the value for order_one.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.sub_order_sn
     *
     * @return the value of order_one.sub_order_sn
     *
     * @mbg.generated
     */
    public String getSubOrderSn() {
        return subOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.sub_order_sn
     *
     * @param subOrderSn the value for order_one.sub_order_sn
     *
     * @mbg.generated
     */
    public void setSubOrderSn(String subOrderSn) {
        this.subOrderSn = subOrderSn == null ? null : subOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.product_id
     *
     * @return the value of order_one.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.product_id
     *
     * @param productId the value for order_one.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.terrace
     *
     * @return the value of order_one.terrace
     *
     * @mbg.generated
     */
    public String getTerrace() {
        return terrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.terrace
     *
     * @param terrace the value for order_one.terrace
     *
     * @mbg.generated
     */
    public void setTerrace(String terrace) {
        this.terrace = terrace == null ? null : terrace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.user_id
     *
     * @return the value of order_one.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.user_id
     *
     * @param userId the value for order_one.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.commission_total_pre
     *
     * @return the value of order_one.commission_total_pre
     *
     * @mbg.generated
     */
    public BigDecimal getCommissionTotalPre() {
        return commissionTotalPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.commission_total_pre
     *
     * @param commissionTotalPre the value for order_one.commission_total_pre
     *
     * @mbg.generated
     */
    public void setCommissionTotalPre(BigDecimal commissionTotalPre) {
        this.commissionTotalPre = commissionTotalPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.commission_total_real
     *
     * @return the value of order_one.commission_total_real
     *
     * @mbg.generated
     */
    public BigDecimal getCommissionTotalReal() {
        return commissionTotalReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.commission_total_real
     *
     * @param commissionTotalReal the value for order_one.commission_total_real
     *
     * @mbg.generated
     */
    public void setCommissionTotalReal(BigDecimal commissionTotalReal) {
        this.commissionTotalReal = commissionTotalReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.title
     *
     * @return the value of order_one.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.title
     *
     * @param title the value for order_one.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.order_status
     *
     * @return the value of order_one.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.order_status
     *
     * @param orderStatus the value for order_one.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.is_commission
     *
     * @return the value of order_one.is_commission
     *
     * @mbg.generated
     */
    public String getIsCommission() {
        return isCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.is_commission
     *
     * @param isCommission the value for order_one.is_commission
     *
     * @mbg.generated
     */
    public void setIsCommission(String isCommission) {
        this.isCommission = isCommission == null ? null : isCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.product_img
     *
     * @return the value of order_one.product_img
     *
     * @mbg.generated
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.product_img
     *
     * @param productImg the value for order_one.product_img
     *
     * @mbg.generated
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.payment_price
     *
     * @return the value of order_one.payment_price
     *
     * @mbg.generated
     */
    public String getPaymentPrice() {
        return paymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.payment_price
     *
     * @param paymentPrice the value for order_one.payment_price
     *
     * @mbg.generated
     */
    public void setPaymentPrice(String paymentPrice) {
        this.paymentPrice = paymentPrice == null ? null : paymentPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.commission_time
     *
     * @return the value of order_one.commission_time
     *
     * @mbg.generated
     */
    public Date getCommissionTime() {
        return commissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.commission_time
     *
     * @param commissionTime the value for order_one.commission_time
     *
     * @mbg.generated
     */
    public void setCommissionTime(Date commissionTime) {
        this.commissionTime = commissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_one.reality_commission_time
     *
     * @return the value of order_one.reality_commission_time
     *
     * @mbg.generated
     */
    public Date getRealityCommissionTime() {
        return realityCommissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_one.reality_commission_time
     *
     * @param realityCommissionTime the value for order_one.reality_commission_time
     *
     * @mbg.generated
     */
    public void setRealityCommissionTime(Date realityCommissionTime) {
        this.realityCommissionTime = realityCommissionTime;
    }
}