package com.social.commission.api.po;

import java.math.BigDecimal;
import java.util.Date;

public class sdfdfs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_detail_id
     *
     * @mbg.generated
     */
    private Long commissionDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.order_code
     *
     * @mbg.generated
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_type
     *
     * @mbg.generated
     */
    private String commissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_direction
     *
     * @mbg.generated
     */
    private String commissionDirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.batch_code
     *
     * @mbg.generated
     */
    private String batchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_status
     *
     * @mbg.generated
     */
    private String commissionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_user_id
     *
     * @mbg.generated
     */
    private Long commissionUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_user_order
     *
     * @mbg.generated
     */
    private Integer commissionUserOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.member_level
     *
     * @mbg.generated
     */
    private String memberLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_rate
     *
     * @mbg.generated
     */
    private Long commissionRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_amount_pre
     *
     * @mbg.generated
     */
    private BigDecimal commissionAmountPre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_amount_real
     *
     * @mbg.generated
     */
    private BigDecimal commissionAmountReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_code
     *
     * @mbg.generated
     */
    private String commissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_detail_id
     *
     * @return the value of commission_detail.commission_detail_id
     *
     * @mbg.generated
     */
    public Long getCommissionDetailId() {
        return commissionDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_detail_id
     *
     * @param commissionDetailId the value for commission_detail.commission_detail_id
     *
     * @mbg.generated
     */
    public void setCommissionDetailId(Long commissionDetailId) {
        this.commissionDetailId = commissionDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.tenant_id
     *
     * @return the value of commission_detail.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.tenant_id
     *
     * @param tenantId the value for commission_detail.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.order_code
     *
     * @return the value of commission_detail.order_code
     *
     * @mbg.generated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.order_code
     *
     * @param orderCode the value for commission_detail.order_code
     *
     * @mbg.generated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_type
     *
     * @return the value of commission_detail.commission_type
     *
     * @mbg.generated
     */
    public String getCommissionType() {
        return commissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_type
     *
     * @param commissionType the value for commission_detail.commission_type
     *
     * @mbg.generated
     */
    public void setCommissionType(String commissionType) {
        this.commissionType = commissionType == null ? null : commissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_direction
     *
     * @return the value of commission_detail.commission_direction
     *
     * @mbg.generated
     */
    public String getCommissionDirection() {
        return commissionDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_direction
     *
     * @param commissionDirection the value for commission_detail.commission_direction
     *
     * @mbg.generated
     */
    public void setCommissionDirection(String commissionDirection) {
        this.commissionDirection = commissionDirection == null ? null : commissionDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.batch_code
     *
     * @return the value of commission_detail.batch_code
     *
     * @mbg.generated
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.batch_code
     *
     * @param batchCode the value for commission_detail.batch_code
     *
     * @mbg.generated
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_status
     *
     * @return the value of commission_detail.commission_status
     *
     * @mbg.generated
     */
    public String getCommissionStatus() {
        return commissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_status
     *
     * @param commissionStatus the value for commission_detail.commission_status
     *
     * @mbg.generated
     */
    public void setCommissionStatus(String commissionStatus) {
        this.commissionStatus = commissionStatus == null ? null : commissionStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_user_id
     *
     * @return the value of commission_detail.commission_user_id
     *
     * @mbg.generated
     */
    public Long getCommissionUserId() {
        return commissionUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_user_id
     *
     * @param commissionUserId the value for commission_detail.commission_user_id
     *
     * @mbg.generated
     */
    public void setCommissionUserId(Long commissionUserId) {
        this.commissionUserId = commissionUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_user_order
     *
     * @return the value of commission_detail.commission_user_order
     *
     * @mbg.generated
     */
    public Integer getCommissionUserOrder() {
        return commissionUserOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_user_order
     *
     * @param commissionUserOrder the value for commission_detail.commission_user_order
     *
     * @mbg.generated
     */
    public void setCommissionUserOrder(Integer commissionUserOrder) {
        this.commissionUserOrder = commissionUserOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.member_level
     *
     * @return the value of commission_detail.member_level
     *
     * @mbg.generated
     */
    public String getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.member_level
     *
     * @param memberLevel the value for commission_detail.member_level
     *
     * @mbg.generated
     */
    public void setMemberLevel(String memberLevel) {
        this.memberLevel = memberLevel == null ? null : memberLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_rate
     *
     * @return the value of commission_detail.commission_rate
     *
     * @mbg.generated
     */
    public Long getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_rate
     *
     * @param commissionRate the value for commission_detail.commission_rate
     *
     * @mbg.generated
     */
    public void setCommissionRate(Long commissionRate) {
        this.commissionRate = commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_amount_pre
     *
     * @return the value of commission_detail.commission_amount_pre
     *
     * @mbg.generated
     */
    public BigDecimal getCommissionAmountPre() {
        return commissionAmountPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_amount_pre
     *
     * @param commissionAmountPre the value for commission_detail.commission_amount_pre
     *
     * @mbg.generated
     */
    public void setCommissionAmountPre(BigDecimal commissionAmountPre) {
        this.commissionAmountPre = commissionAmountPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_amount_real
     *
     * @return the value of commission_detail.commission_amount_real
     *
     * @mbg.generated
     */
    public BigDecimal getCommissionAmountReal() {
        return commissionAmountReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_amount_real
     *
     * @param commissionAmountReal the value for commission_detail.commission_amount_real
     *
     * @mbg.generated
     */
    public void setCommissionAmountReal(BigDecimal commissionAmountReal) {
        this.commissionAmountReal = commissionAmountReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_code
     *
     * @return the value of commission_detail.commission_code
     *
     * @mbg.generated
     */
    public String getCommissionCode() {
        return commissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_code
     *
     * @param commissionCode the value for commission_detail.commission_code
     *
     * @mbg.generated
     */
    public void setCommissionCode(String commissionCode) {
        this.commissionCode = commissionCode == null ? null : commissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.create_user_id
     *
     * @return the value of commission_detail.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.create_user_id
     *
     * @param createUserId the value for commission_detail.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.create_date
     *
     * @return the value of commission_detail.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.create_date
     *
     * @param createDate the value for commission_detail.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.update_user_id
     *
     * @return the value of commission_detail.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.update_user_id
     *
     * @param updateUserId the value for commission_detail.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.update_date
     *
     * @return the value of commission_detail.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.update_date
     *
     * @param updateDate the value for commission_detail.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.del_flag
     *
     * @return the value of commission_detail.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.del_flag
     *
     * @param delFlag the value for commission_detail.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}