package com.social.commission.api.po;

import java.math.BigDecimal;

public class SonOrderPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column son_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column son_order.son_order_id
     *
     * @mbg.generated
     */
    private String sonOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column son_order.order_code
     *
     * @mbg.generated
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column son_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    private BigDecimal totalCommission;

    public BigDecimal getTotalCommission() {
        return totalCommission;
    }

    public void setTotalCommission(BigDecimal totalCommission) {
        this.totalCommission = totalCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column son_order.id
     *
     * @return the value of son_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column son_order.id
     *
     * @param id the value for son_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column son_order.son_order_id
     *
     * @return the value of son_order.son_order_id
     *
     * @mbg.generated
     */
    public String getSonOrderId() {
        return sonOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column son_order.son_order_id
     *
     * @param sonOrderId the value for son_order.son_order_id
     *
     * @mbg.generated
     */
    public void setSonOrderId(String sonOrderId) {
        this.sonOrderId = sonOrderId == null ? null : sonOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column son_order.order_code
     *
     * @return the value of son_order.order_code
     *
     * @mbg.generated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column son_order.order_code
     *
     * @param orderCode the value for son_order.order_code
     *
     * @mbg.generated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column son_order.order_id
     *
     * @return the value of son_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column son_order.order_id
     *
     * @param orderId the value for son_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}